services:
  api:
    build:
      context: ./Backend
    container_name: logs-api
    restart: unless-stopped
    environment:
      PORT: 8080
      DATABASE_URL: postgres://postgres:password@postgres:5432/logs
      RABBITMQ_URL: amqp://rabbitmq:5672
    ports:
      - "8080:8080"
    depends_on:
      migrate:
        condition: service_completed_successfully
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "fetch('http://127.0.0.1:8080/docs').then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  worker:
    build:
      context: ./Backend
    container_name: logs-worker
    restart: unless-stopped
    command: ["node", "dist/worker/index.js"]
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432/logs
      RABBITMQ_URL: amqp://rabbitmq:5672
    depends_on:
      migrate:
        condition: service_completed_successfully
      rabbitmq:
        condition: service_healthy

  migrate:
    build:
      context: ./Backend
    container_name: logs-migrate
    restart: "no"
    command: ["npm", "run", "db:migrate"]
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432/logs
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:17
    container_name: logs-db
    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: logs

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d logs"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:4-management
    container_name: logs-rabbitmq
    restart: unless-stopped

    ports:
      - "5672:5672"
      - "15672:15672"
      
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

